language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - composer self-update
  - composer update --no-interaction $COMPOSER_OPTS

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text

after_script:
  - php vendor/bin/coveralls
